import { COLORS } from '../ui/theme.js';
import { t } from '../i18n/i18n.js';

/** Instrument layouts per car (logical px). Each entry names the reading it shows (`source`).
 *  Dials sweep clockwise from `startDeg` to `endDeg` (0 deg = 3 o'clock). */

const SWEEP = { startDeg: 135, endDeg: 405 };
const SMALL_SWEEP = { startDeg: 150, endDeg: 390 };
const LCD = { color: '#ffb52e', ghost: 'rgba(255,181,46,0.07)' };

const smallDial = (x, y, r, source, label, range, extra = {}) => {
    return {
        type: 'dial',
        source,
        x,
        y,
        r,
        ...SMALL_SWEEP,
        ...range,
        label,
        numeralScale: 0.26,
        labelY: 0.5,
        ...extra,
    };
};

const oilDial = (x, y, r, extra) => {
    return smallDial(
        x,
        y,
        r,
        'oil',
        t('general.oil'),
        { min: 0, max: 80, majorStep: 20, minorStep: 10, labelStep: 40 },
        extra,
    );
};
const waterDial = (x, y, r, extra) => {
    return smallDial(
        x,
        y,
        r,
        'water',
        t('general.temp'),
        { min: 0, max: 1, majorStep: 0.5, minorStep: 0.25, labelStep: 2 },
        extra,
    );
};
const fuelDial = (x, y, r, extra) => {
    return smallDial(
        x,
        y,
        r,
        'fuel',
        t('general.fuel'),
        { min: 0, max: 1, majorStep: 0.5, minorStep: 0.25, labelStep: 2 },
        extra,
    );
};

export const CLUSTERS = {
    // The cockpit in the reference screenshot: red numerals, speedo left, tach right, oil and temp between.
    lotus: {
        housing: { x: 175, y: 500, w: 610, h: 250, r: 70 },
        instruments: [
            {
                type: 'dial',
                source: 'speed',
                x: 300,
                y: 625,
                r: 98,
                min: 0,
                max: 180,
                majorStep: 20,
                minorStep: 10,
                labelFrom: 20,
                ...SWEEP,
                numerals: '#e3352a',
                label: t('general.mph'),
            },
            {
                type: 'dial',
                source: 'rpm',
                x: 660,
                y: 625,
                r: 98,
                min: 0,
                max: 8,
                majorStep: 1,
                minorStep: 0.5,
                labelFrom: 1,
                redFrom: 7,
                ...SWEEP,
                numerals: '#e3352a',
                label: t('general.rpm'),
                sublabel: 'x1000',
            },
            oilDial(480, 568, 40),
            waterDial(480, 678, 36),
        ],
        lamps: [
            { x: 268, y: 712, r: 7, color: '#3ee05a', source: 'signal' },
            { x: 300, y: 716, r: 7, color: '#3d7bff', source: 'beam' },
            { x: 332, y: 712, r: 7, color: '#ff3324', source: 'warning' },
        ],
    },
    porsche: {
        housing: { x: 105, y: 500, w: 750, h: 225, r: 110 },
        instruments: [
            fuelDial(178, 612, 58),
            oilDial(318, 602, 70),
            {
                type: 'dial',
                source: 'rpm',
                x: 480,
                y: 592,
                r: 112,
                min: 0,
                max: 8,
                majorStep: 1,
                minorStep: 0.25,
                redFrom: 6.8,
                ...SWEEP,
                numerals: '#f0f0ea',
                label: t('general.rpm'),
                sublabel: 'x1000',
                labelY: -0.38,
            },
            {
                type: 'dial',
                source: 'boost',
                x: 480,
                y: 650,
                r: 34,
                min: 0,
                max: 1,
                majorStep: 0.5,
                minorStep: 0.1,
                labelStep: 2,
                startDeg: 200,
                endDeg: 340,
                label: t('general.turbo'),
                labelY: 0.35,
                numeralScale: 0.2,
            },
            {
                type: 'dial',
                source: 'speed',
                x: 642,
                y: 602,
                r: 96,
                min: 0,
                max: 180,
                majorStep: 20,
                minorStep: 10,
                labelStep: 20,
                ...SWEEP,
                numerals: '#f0f0ea',
                label: t('general.mph'),
            },
            {
                type: 'dial',
                source: 'clock',
                x: 785,
                y: 612,
                r: 58,
                min: 0,
                max: 12,
                majorStep: 1,
                labelStep: 3,
                labelFrom: 3,
                startDeg: -90,
                endDeg: 270,
                numeralScale: 0.24,
                needleLength: 0.6,
            },
        ],
        lamps: [
            { x: 452, y: 700, r: 5, color: '#ff3324', source: 'warning' },
            { x: 480, y: 704, r: 5, color: '#3ee05a', source: 'signal' },
            { x: 508, y: 700, r: 5, color: '#3d7bff', source: 'beam' },
        ],
    },
    ferrari: {
        housing: { x: 170, y: 495, w: 620, h: 250, r: 60 },
        instruments: [
            {
                type: 'dial',
                source: 'speed',
                x: 300,
                y: 615,
                r: 104,
                min: 0,
                max: 200,
                majorStep: 20,
                minorStep: 10,
                labelStep: 40,
                ...SWEEP,
                needle: '#ff8a1c',
                bezel: 'chrome',
                label: t('general.mph'),
            },
            {
                type: 'dial',
                source: 'rpm',
                x: 660,
                y: 615,
                r: 104,
                min: 0,
                max: 10,
                majorStep: 1,
                minorStep: 0.5,
                redFrom: 6.8,
                ...SWEEP,
                needle: '#ff8a1c',
                bezel: 'chrome',
                label: t('general.rpm'),
                sublabel: 'x1000',
            },
            oilDial(446, 562, 31, { needle: '#ff8a1c' }),
            waterDial(514, 562, 31, { needle: '#ff8a1c' }),
            smallDial(
                446,
                668,
                31,
                'oilTemp',
                t('general.oil'),
                { min: 0, max: 1, majorStep: 0.5, labelStep: 2 },
                { needle: '#ff8a1c' },
            ),
            fuelDial(514, 668, 31, { needle: '#ff8a1c' }),
        ],
        lamps: [
            { x: 480, y: 615, r: 6, color: '#ff3324', source: 'warning' },
            { x: 480, y: 728, r: 5, color: '#3ee05a', source: 'signal' },
        ],
    },
    lamborghini: {
        housing: { x: 160, y: 492, w: 640, h: 258, r: 26 },
        instruments: [
            {
                type: 'dial',
                source: 'speed',
                x: 292,
                y: 615,
                r: 100,
                min: 0,
                max: 200,
                majorStep: 20,
                minorStep: 10,
                labelStep: 20,
                ...SWEEP,
                needle: '#ff5a1f',
                numeralScale: 0.14,
                label: t('general.mph'),
            },
            {
                type: 'dial',
                source: 'rpm',
                x: 668,
                y: 615,
                r: 100,
                min: 0,
                max: 10,
                majorStep: 1,
                minorStep: 0.5,
                redFrom: 7.5,
                ...SWEEP,
                needle: '#ff5a1f',
                label: t('general.rpm'),
                sublabel: 'x1000',
            },
            oilDial(480, 545, 30, { needle: '#ff5a1f' }),
            waterDial(480, 615, 30, { needle: '#ff5a1f' }),
            fuelDial(480, 685, 30, { needle: '#ff5a1f' }),
        ],
        lamps: [
            { x: 205, y: 720, r: 6, color: '#ff3324', source: 'warning' },
            { x: 230, y: 720, r: 6, color: '#3ee05a', source: 'signal' },
            { x: 755, y: 720, r: 6, color: '#3d7bff', source: 'beam' },
        ],
    },
    // The C4's liquid-crystal cluster: digital speed, bar-graph tach, four readouts in the centre.
    corvette: {
        housing: { x: 175, y: 505, w: 610, h: 235, r: 30 },
        instruments: [
            {
                type: 'bar',
                source: 'speed',
                max: 85,
                x: 205,
                y: 640,
                w: 215,
                h: 46,
                segments: 24,
                curve: 26,
                ghost: 'rgba(120,255,160,0.06)',
                colors: [[1, '#59ff8a']],
            },
            { type: 'digits', source: 'speed', x: 400, y: 712, size: 48, width: 3, ...LCD },
            { type: 'text', text: t('general.mph'), x: 404, y: 712, size: 14, color: LCD.color },
            {
                type: 'bar',
                source: 'rpm',
                max: 6,
                x: 545,
                y: 640,
                w: 215,
                h: 46,
                segments: 24,
                curve: 26,
                ghost: 'rgba(120,255,160,0.06)',
                colors: [
                    [0.62, '#59ff8a'],
                    [0.8, '#ffd23a'],
                    [1, '#ff4030'],
                ],
            },
            { type: 'digits', source: 'rpm', format: 'rpm', x: 740, y: 712, size: 34, width: 4, ...LCD },
            { type: 'text', text: t('general.rpm'), x: 744, y: 712, size: 14, color: LCD.color },
            { type: 'digits', source: 'oil', x: 512, y: 560, size: 22, width: 2, ...LCD },
            { type: 'text', text: t('general.oil'), x: 448, y: 560, size: 12, color: LCD.color },
            { type: 'digits', source: 'water', format: 'temp', x: 512, y: 600, size: 22, width: 3, ...LCD },
            { type: 'text', text: t('general.temp'), x: 448, y: 600, size: 12, color: LCD.color },
            { type: 'digits', source: 'volts', format: 'volts', x: 512, y: 640, size: 22, width: 4, ...LCD },
            { type: 'text', text: t('general.volts'), x: 448, y: 640, size: 12, color: LCD.color },
            {
                type: 'bar',
                source: 'fuel',
                max: 1,
                x: 442,
                y: 700,
                w: 76,
                h: 16,
                segments: 10,
                ghost: 'rgba(255,181,46,0.07)',
                colors: [
                    [0.2, '#ff4030'],
                    [1, LCD.color],
                ],
            },
        ],
        lamps: [
            { x: 480, y: 728, r: 6, color: COLORS.accent, source: 'overdrive' },
            { x: 215, y: 525, r: 5, color: '#ff3324', source: 'warning' },
        ],
    },
};
